/**
 * Sample data for development
 * In production, this would come from Airtable API
 */

export const SAMPLE_PEOPLE = [
  {
    id: 1,
    name: 'Ramesh Premaratna',
    jobTitle: 'In-house Creative',
    tribe: 'Brand',
    chapterLead: 'Mike Kevan',
    startDate: '10 Oct 2022',
    status: 'Ongoing',
    salary: 90000,
    hours: 40,
    kiwiSaver: true,
    allowances: 0,
    marginPercent: 5,
  },
  {
    id: 2,
    name: 'Sean Ingram',
    jobTitle: 'Social Partner',
    tribe: 'Brand',
    chapterLead: 'Olivia Wright',
    startDate: '14 Mar 2025',
    status: 'Ongoing',
    salary: 66000,
    hours: 40,
    kiwiSaver: false,
    allowances: 0,
    marginPercent: 5,
  },
  {
    id: 3,
    name: 'Rimma Bosomworth',
    jobTitle: 'Marketing Automation',
    tribe: 'Customer',
    chapterLead: 'Akshay',
    startDate: '5 May 2025',
    status: 'Ongoing',
    salary: 80000,
    hours: 40,
    kiwiSaver: true,
    allowances: 0,
    marginPercent: 5,
  },
  {
    id: 4,
    name: 'Nick Boulstridge',
    jobTitle: 'Sales Enablement',
    tribe: 'Business',
    chapterLead: 'Travena',
    startDate: '6 Oct 2025',
    status: 'Fixed Term',
    salary: 230528,
    hours: 15,
    kiwiSaver: true,
    allowances: 40,
    marginPercent: 5,
  },
];
